server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8999/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true 
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://34.72.40.154"   
              - "http://136.111.61.239" 
              - "http://localhost:7070"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: toolrent-backend
          uri: lb://toolrent-backend
          predicates:
            - Path=/api/**
        - id: keycloak-route
          uri: http://keycloak:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: toolrent-frontend-assets
          uri: http://toolrent-frontend:80
          predicates:
            - Path=/assets/**, /static/**, /favicon.ico, /index.html
        - id: toolrent-frontend-main
          uri: http://toolrent-frontend:80
          predicates:
            - Path=/**
          order: 100

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://136.111.61.239/auth/realms/ToolRent

# Debugging
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes"
  endpoint:
    gateway:
      enabled: true
  health:
    show-details: always