server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8999/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true 
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "*" # Permite todo por ahora para evitar problemas con IPs de Nodos cambiantes
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false # Si usas '*' en origins, credentials debe ser false usualmente, o especifica la IP exacta del nodo
            maxAge: 3600

      routes:
        # SOLO queda la ruta al backend
        - id: toolrent-backend
          uri: lb://toolrent-backend
          predicates:
            - Path=/api/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # IMPORTANTE: Esto debe coincidir con KC_HOSTNAME_URL de Keycloak.
          # Si Keycloak está en el nodo X puerto 30001, el token tendrá ese issuer.
          # El Gateway debe ser capaz de alcanzar esa URL para descargar las claves públicas.
          issuer-uri: http://<TU_IP_DE_NODO_GKE>:30001/realms/ToolRent

# Debugging
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes"