server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8999/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true 
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://35.238.245.65:30002"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
            
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        - id: toolrent-backend
          uri: lb://toolrent-backend
          predicates:
            - Path=/api/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # Esto debe coincidir con KC_HOSTNAME_URL de Keycloak.
          issuer-uri: http://35.238.245.65:30001/realms/ToolRent

# Debugging
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes"