server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8999/eureka
  instance:
    prefer-ip-address: true
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: backend-service
          uri: lb://toolrent-backend
          predicates:
            - Path=/api/**