server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8999/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        # Importante: Esta propiedad ayuda a que peticiones OPTIONS pasen siempre
        add-to-simple-url-handler-mapping: true 
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://34.29.108.227"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: toolrent-backend
          uri: lb://toolrent-backend
          predicates:
            - Path=/api/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.42.204.49/realms/ToolRent
          jwk-set-uri: http://keycloak:8080/realms/ToolRent/protocol/openid-connect/certs