server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8999/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        # Importante: Esta propiedad ayuda a que peticiones OPTIONS pasen siempre
        add-to-simple-url-handler-mapping: true 
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://34.72.40.154"
              - "http://localhost:7070"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: toolrent-backend
          uri: lb://toolrent-backend
          predicates:
            - Path=/api/**
        -id: toolrent-frontend-static
          uri: http://toolrent-frontend:80
          predicates:
            - Path=/static/**,/assets/**,/index.html,/favicon.ico,/manifest.json,/robots.txt
        -id: toolrent-frontend-root
          uri: http://toolrent-frontend:80
          predicates:
            - Path=/
            - Method=GET
        - id: toolrent-frontend
          uri: http://toolrent-frontend:80
          predicates:
            - Path=/**
          order: 100

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.27.203.192/realms/ToolRent