server:
  port: 6060

spring:
  application:
    name: toolrent-backend
  
  # --- BASE DE DATOS ---
  datasource:
    url: jdbc:postgresql://postgres:5432/toolrent
    username: postgres
    password: SQLHolaYo64
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  
  # --- JPA / HIBERNATE ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  # --- SEGURIDAD (Spring Security 6 / Boot 3) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ToolRent
          jwk-set-uri: http://keycloak:8080/realms/ToolRent/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: toolrent-backend
            client-secret: WXo5KsY1eqSHj9rHBqfS1E3R44FNd5lW
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ToolRent

# --- EUREKA ---
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Apuntando al nombre correcto del servicio k8s y puerto 8999
      defaultZone: http://eureka-service:8999/eureka/

# --- TUS VARIABLES PERSONALIZADAS (Legacy) ---
keycloak:
  realm: ToolRent
  auth-server-url: http://keycloak:8080
  resource: ToolRent-backend
  credentials:
    secret: WXo5KsY1eqSHj9rHBqfS1E3R44FNd5lW
  # Esta variable la usabas en tu properties original para resolver placeholders
  client-secret: WXo5KsY1eqSHj9rHBqfS1E3R44FNd5lW

# --- JWT CONVERTER (Roles) ---
jwt:
  auth:
    converter:
      resource-id: ToolRent-backend
      principle-attribute: preferred_username

# --- CORS ---
spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# --- ACTUATOR ---
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true